Controllers/PacoteController.cs
using System.Collections.Generic;
using atividade2CRUD.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;

namespace atividade2CRUD.Controllers


{
    public class PacoteController : Controller {

        public IActionResult Lista(){
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login", "Usuario");
            PacoteBanco pacoteBanco = new PacoteBanco();
            List<Pacote> Lista = pacoteBanco.Listar();
            return View(Lista);
        }

        public IActionResult Cadastro(){
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login", "Usuario");
            return View();
        }

        [HttpPost]
        public IActionResult Cadastro(Pacote pacote){
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login", "Usuario");
            PacoteBanco pacoteBanco = new PacoteBanco();
            int idUsuario = HttpContext.Session.GetInt32("IdUsuario") ?? 0;
            pacote.Id = idUsuario;
            pacoteBanco.Inserir(pacote);
            ViewBag.Mensagem = "Cadastro realizado com sucesso";
            return View();
        }

        public IActionResult Editar(int id_pacotes){
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login");
            PacoteBanco pacoteBanco = new PacoteBanco();
            Pacote pacote = pacoteBanco.BuscarPorId(id_pacotes);
            return View(pacote);
        }

        [HttpPost]
        public IActionResult Editar(Pacote pacote){
            if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login");
            PacoteBanco pacoteBanco = new PacoteBanco();
            pacoteBanco.Atualizar(pacote);
            ViewBag.Mensagem = "Pacote atualizado";
            return RedirectToAction("Lista");
        }

        public IActionResult Remover(int id_pacotes){
             if(HttpContext.Session.GetInt32("IdUsuario") == null)
                return RedirectToAction("Login");
            PacoteBanco pacoteBanco = new PacoteBanco();
            pacoteBanco.Remover( id_pacotes);

            return RedirectToAction("Lista");
        }



        public IActionResult Login(){
            return View();
        }

        [HttpPost]
        public IActionResult Login(Usuario usuario){
            UsuarioBanco usuarioBanco = new UsuarioBanco();
            Usuario usuarioSessao = usuarioBanco.ValidarLogin(usuario);

            if(usuario != null){
                ViewBag.Mensagem = "Você esta logado";
                HttpContext.Session.SetInt32("IdUsuario", usuarioSessao.Id);
                HttpContext.Session.SetString("NomeUsuario", usuarioSessao.Nome);

                return Redirect("Cadastro");
            }else{
                ViewBag.Mensagem = "Falha no Login";
                return View();
            }
        }

        public IActionResult Logout(){
            HttpContext.Session.Clear();
            return RedirectToAction("Login", "Usuario");
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;


<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] Destino Certo </title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/atividade_2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> Destino Certo </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Usuario" asp-action="Login">Login</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacote" asp-action="Cadastro">Cadastro</a>
                        </li>
                          <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Pacote" asp-action="Lista">Lista</a>
                        </li>
                        <li class="nav-item">
                            @if(Context.Session.GetInt32("IdUsuario") != null){ 
                                <p> Olá, @Context.Session.GetString("NomeUsuario") - <a asp-action="Logout"> Sair </a></p>
                            }
                        </li>
                    </ul>

                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - atividade_2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>